create-config 実行結果を DocumentServer 上で確認できる機能を追加

diff --git a/bin/create-config b/bin/create-config
--- a/bin/create-config
+++ b/bin/create-config
@@ -3,31 +3,44 @@ set -e
 
 BASE_DIR=$(cd $(dirname $0)/..; pwd)
 source ${BASE_DIR}/bin/lib/init-env
+LOG_FILE=${BASE_DIR}/config.log
 
-echo ""
-echo "*** STEP 1 ***"
-${BIN_DIR}/destroy-service
+function handle_error() {
+  if [ ${PIPESTATUS[0]} -ne 0 ]; then
+    echo ""                 | tee -a ${LOG_FILE}
+    echo ""                 | tee -a ${LOG_FILE}
+    echo "*** ERROR!! ***"  | tee -a ${LOG_FILE}
+    ${LIB_DIR}/start-document-server
+    exit 1
+  fi
+}
 
-echo ""
-echo "*** STEP 2 ***"
-${LIB_DIR}/init-config $1
+echo ""                                 | tee ${LOG_FILE}
+echo "*** STEP 1 ***"                   | tee -a ${LOG_FILE}
+${BIN_DIR}/destroy-service 2>&1         | tee -a ${LOG_FILE} && handle_error
 
-echo ""
-echo "*** STEP 3 ***"
-${BIN_DIR}/up-service
+echo ""                                 | tee -a ${LOG_FILE}
+echo "*** STEP 2 ***"                   | tee -a ${LOG_FILE}
+${LIB_DIR}/init-config $1 2>&1          | tee -a ${LOG_FILE} && handle_error
 
-echo ""
-echo "*** STEP 4 ***"
-${LIB_DIR}/update-jenkins-plugins
+echo ""                                 | tee -a ${LOG_FILE}
+echo "*** STEP 3 ***"                   | tee -a ${LOG_FILE}
+${BIN_DIR}/up-service 2>&1              | tee -a ${LOG_FILE} && handle_error
 
-echo ""
-echo "*** STEP 5 ***"
-${LIB_DIR}/setup
+echo ""                                 | tee -a ${LOG_FILE}
+echo "*** STEP 4 ***"                   | tee -a ${LOG_FILE}
+${LIB_DIR}/update-jenkins-plugins 2>&1  | tee -a ${LOG_FILE} && handle_error
 
-echo ""
-echo "*** STEP 6 ***"
-${BIN_DIR}/stop-service
+echo ""                                 | tee -a ${LOG_FILE}
+echo "*** STEP 5 ***"                   | tee -a ${LOG_FILE}
+${LIB_DIR}/setup 2>&1                   | tee -a ${LOG_FILE} && handle_error
+
+echo ""                                 | tee -a ${LOG_FILE}
+echo "*** STEP 6 ***"                   | tee -a ${LOG_FILE}
+${BIN_DIR}/stop-service 2>&1            | tee -a ${LOG_FILE} && handle_error
+
+echo ""                                 | tee -a ${LOG_FILE}
+echo ""                                 | tee -a ${LOG_FILE}
+echo "*** Done. ***"                    | tee -a ${LOG_FILE}
+
 ${LIB_DIR}/start-document-server
-
-echo ""
-echo "*** Done. ***"
